# Generated by Django 2.1.4 on 2018-12-19 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kickstartercampaign',
            name='currency_symbol',
        ),
        migrations.RemoveField(
            model_name='kickstartercampaign',
            name='currency_trailing_code',
        ),
        migrations.RemoveField(
            model_name='kickstartercampaign',
            name='friends',
        ),
        migrations.RemoveField(
            model_name='kickstartercampaign',
            name='is_backing',
        ),
        migrations.RemoveField(
            model_name='kickstartercampaign',
            name='is_starrable',
        ),
        migrations.RemoveField(
            model_name='kickstartercampaign',
            name='is_starred',
        ),
        migrations.RemoveField(
            model_name='kickstartercampaign',
            name='permissions',
        ),
    ]
